// <auto-generated />
using System;
using Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251111174718_UserApply")]
    partial class UserApply
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Transactions", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("CreatedAT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("Nvarchar")
                        .HasColumnName("Description");

                    b.Property<DateTime>("SystemDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("SystemDate");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transactionType");

                    b.Property<decimal>("TransactionValue")
                        .HasColumnType("decimal")
                        .HasColumnName("TransactionValue");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("Nvarchar")
                        .HasColumnName("UserEmail");

                    b.Property<int>("TransactionIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransactionIdId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Core.ValueObjects.UserVO.TransactionId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransactionId");
                });

            modelBuilder.Entity("Core.Entities.Transactions", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany("Transaction")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("TransactionsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.HasOne("Core.ValueObjects.UserVO.TransactionId", "TransactionId")
                        .WithMany()
                        .HasForeignKey("TransactionIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionId");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("TransactionsList");
                });
#pragma warning restore 612, 618
        }
    }
}
